#!/bin/bash

# This script creates symbolic links for configuration files

# to ensure that user is running the script with sudo
if [ $EUID -ne 0 ]; then
    echo "$0 is not running as root. Use sudo."
    exit 2
fi

# creating symbolic links for configuration files
ln -s /path/to/bin ~/bin
ln -s /path/to/config ~/.config
ln -s /path/to/home/bashrc ~/.bashrc

echo "Sucessfully created symbolic links"